import { readFileSystem } from "../utilities/readFileSystem";
import fs from "fs-extra";

export async function generate(options: { silent?: boolean } = {}) {
	/**
	 * Generate version
	 */
	const version = JSON.parse(fs.readFileSync("package.json", "utf8")).version;
	fs.writeFileSync(
		"source/version.ts",
		`export const version = "${version}";\n`,
	);

	/**
	 * Generate templates
	 */
	const templatesData = await readFileSystem("templates");
	if (!templatesData) {
		console.error(`❌ Could not read templates. Are you in "gravity/core"?`);
		return;
	}

	const generatedFileWarning = `/**
 * This file is automatically generated from files in the "/packages/gravity/templates" directory.
 * ⛔️  Don't edit it manually! ⛔️
 * Instead edit the templates in "/packages/gravity/templates" and run "generate" or "build".
 */
`;

	const templatesContent =
		generatedFileWarning +
		`export const templates = ${JSON.stringify(templatesData, null, 2)};\n`;

	fs.writeFileSync("source/cli/templates.ts", templatesContent);

	if (!options.silent) console.log("✨ Templates generated");
}
